# Generated by Django 3.1.1 on 2020-09-30 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailValidation',
            fields=[
                ('ValidationId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=60, unique=True)),
            ],
        ),
    ]
