# Generated by Django 3.1 on 2020-09-28 04:48

from django.db import migrations, models
import userinfo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('college_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('profile_img', models.ImageField(blank=True, upload_to=userinfo.models.upload_rename)),
                ('varified_user', models.BooleanField(default=False)),
            ],
        ),
    ]
